package com.openfinance.payments.domain.enums;

public enum EnumConsentRejectionReasonType {
    AUTENTICACAO_DIVERGENTE,
    VALOR_INVALIDO,
    NAO_INFORMADO,
    FALHA_INFRAESTRUTURA,
    TEMPO_EXPIRADO_AUTORIZACAO,
    TEMPO_EXPIRADO_CONSUMO,
    REJEITADO_USUARIO,
    CONTAS_ORIGEM_DESTINO_IGUAIS,
    CONTA_NAO_PERMITE_PAGAMENTO,
    SALDO_INSUFICIENTE,
    VALOR_ACIMA_LIMITE,
    QRCODE_INVALIDO
}
