package com.openfinance.common.domain.enums;

public enum EnumPaymentRejectionReasonType {
    SALDO_INSUFICIENTE,
    VALOR_ACIMA_LIMITE,
    VALOR_INVALIDO,
    COBRANCA_INVALIDA,
    NAO_INFORMADO,
    PAGAMENTO_DIVERGENTE_CONSENTIMENTO,
    DETALHE_PAGAMENTO_INVALIDO,
    PAGAMENTO_RECUSADO_DETENTORA,
    PAGAMENTO_RECUSADO_SPI,
    FALHA_INFRAESTRUTURA,
    FALHA_INFRAESTRUTURA_SPI,
    FALHA_INFRAESTRUTURA_DICT,
    FALHA_INFRAESTRUTURA_ICP,
    FALHA_INFRAESTRUTURA_PSP_RECEBEDOR,
    FALHA_INFRAESTRUTURA_DETENTORA,
    CONTAS_ORIGEM_DESTINO_IGUAIS,
    FALHA_AGENDAMENTO_PAGAMENTOS,
    CHAVE_PIX_DIVERGENTE_AGENDAMENTO_LIQUIDACAO,
    CONTA_NAO_PERMITE_PAGAMENTO,
    QRCODE_INVALIDO
}
